### ISSUE TITLE
SDK 2.0 next button missing

### ISSUE THREAD

**Issue by wsykes** [articulate/storyline-sdk#3]
Hi 
I believe I have found an issue.
When I publish the customFrame flash file and swap the Artiuclate SWF with the new SWF the next button is always missing when viewing the published articulate resource

Original swf looks like this
![before](https://cloud.githubusercontent.com/assets/912170/13819249/c7dc516a-eb90-11e5-9532-f325abdd0c54.png)

swf from SDK looks like this
![after](https://cloud.githubusercontent.com/assets/912170/13819397/1993289e-eb91-11e5-999b-f892046b0554.png)

This is without making any amendments to the flash file.

Please could someone let me know if I am missing something?

It seems like the buttons are pushing each other over.  If I turn off the submit button the next button appears on the stage

Regards

Wes

**Comment by robsheely** [comment]
Hi, @wsykes, I'm the programmer who created the SDK. Can you zip the folder with the output for your project and attach it to a comment? I will take a look and see if I can figure out what's going on.

**Comment by wsykes** [comment]
Morning Rob

I gave up on the SDK after a few days of struggling.  I deleted all of my attempts then got a reply from yourself.  I tried to replicate  the error I was having which I thought would be a simple task because nothing I tried worked previously (not even publishing the untouched file worked last week).
This morning however it is working exactly as I wanted it to.

I know what the issue is now.

When using the standard Articulate stage size  720x540 (4:3),  the buttons on the far right in the control button section of the SDK get cut off.  When I changed my stage size to 800 x 600 then they are exposed.

Do you still need me to send an example or can you replicate this?

Regards

Wes

**Comment by robsheely** [comment]
@wsykes Wes, thanks, I'll look at it.

Rob

**Comment by robsheely** [comment]
@wsykes Wes, I think I understand the confusion. The Articulate frame is published at a different size than the slide size. The customary slide size is 720x540 and the frame is 980x658. If you set your stage size to 980x658, everything should be well.

When creating the sample frame in the SDK, we deliberately tried to keep it simple and didn't include any functionality for different sizes. If you want to create a different-sized frame, you'll need to manually position the elements to fit where you want them within your new frame size.

Hopefully, this answer won't prove a disappointment. Let me know if there'a anything else I can help you with.

Rob

**Comment by wsykes** [comment]
Thanks for looking into this Rob.

Have a great Easter ☺

Regards

Wes
